### PR TITLE
enhance(build): implemented additional build fields in recent build history

### PR DESCRIPTION
**Pull request by davidvader**
closes https://github.com/go-vela/community/issues/145

## Changes
- added host
- added branch
- added commit sha

Screen Shot 2020-11-05 at 3 57 23 PM

### CODE REVIEW

**Comment by davidvader** [comment]
waiting on #229 then verifying style across browsers etc.

**Comment by JordanSussman** [comment]
I do wonder if `host` should be updated to `agent` to avoid some confusion.

**Comment by kneal** [comment]
I agree with @JordanSussman. I think _host_ makes sense to admins but the user would probably not understand what that field means.

**Comment by davidvader** [comment]
I can agree with that, good point! I think worker is the most accurate alternative.

**Comment by davidvader** [comment]
pr cleaned up, some changes from the demo have been reverted. rfr

**Review by jbrockopp — APPROVED** [review]
LGTM

**Review by kneal — APPROVED** [review]
LGTM 🐬

**Pull request merged**
