### PR TITLE
enhance(crumbs): rework secrets breadcrumbs

### PR DESCRIPTION
**Pull request by davidvader**
# Secrets Crumb Refactor proposal

Vela UI needs a better way of handling Secrets navigation, and part of the problem is confusing breadcrumbs. 

## Problems

1. Navigating from Repo Builds -> Repo Secrets is one-way, the repo crumb updates to Repo Secrets rather than staying the same link which is misleading.
2. Navigating from Repo Secrets -> Org Secrets is one-way.
3. Too many URL values are reflected in the crumb. With the new plugin support for secret engines the UI should focus on internal, native secrets. 
4. Navigating to secrets pages creates closed loop, or a dead-end from Overview -> View repo secret

## Potential Designs

_Below are the ideas for how secrets crumbs could look and behave._

### Current

For reference, here is the current crumbs architecture, as well as repo builds and hooks for additional comparison.

| Page  | URL | Breadcrumb |
| ------------- | ------------- |  ------------- |
| Repo Builds  | *vela.net/go-vela/ui*  | Overview / go-vela / ui | 
| Repo Hooks  | *vela.net/go-vela/ui/hooks* | Overview / go-vela / ui / Hooks | 
| View Repo Secrets  | *vela.net/-/secrets/native/repo/go-vela/ui* | Overview / Secrets / native / repo / go-vela / ui | 
| Add Repo Secret  | *vela.net/-/secrets/native/repo/go-vela/ui/add* | Overview / Secrets / native / repo / go-vela / ui / Add | 
| Edit Repo Secret  | *vela.net/-/secrets/native/repo/go-vela/ui/docker_password* | Overview / Secrets / native / repo / go-vela / ui / docker_password | 

As a part of the current crumb implementation, when viewing *ANY* secrets page, the crumbs redirect to secrets pages. For example, see this breadcrumb trail for viewing Repo Secrets for go-vela/ui
 ``` Overview / Secrets / native / repo / go-vela / ui ``` 
`go-vela` would direct to Org Secrets for go-vela, which can be misleading, and leads to a navigation dead end.

### Proposed Options

Here are the proposed options, but open to any feedback/suggestions.

#### Crumbs

| Page  | URL | Breadcrumb Option 1 | Breadcrumb Option 2 |
| ------------- | ------------- |  ------------- |  ------------- |
| View Repo Secrets  | *vela.net/-/secrets/native/repo/go-vela/ui* | Overview  / go-vela / ui / Repo Secrets |  Overview  / go-vela / ui / Secrets | 
| Add Repo Secret  | *vela.net/-/secrets/native/repo/go-vela/ui/add* | Overview / go-vela / ui / Add Repo Secret |  Overview / go-vela / ui / Secrets / Add | 
| Edit Repo Secret  | *vela.net/-/secrets/native/repo/go-vela/ui/docker_password* | Overview / go-vela / ui /  Secrets / docker_password | Overview / go-vela / ui /  Secrets / Edit | 

And same would follow for Org/Shared secrets.

#### Functionality

In addition to changing the crumb structure, I also propose we make repos in the crumb trail link to Repo Builds, rather than Repo secrets, and adapt that same logic to the other crumbs. 

### Caveats

- Some of these changes would require some tweaks/additional components to navigate between viewing/adding/editing secrets, due to changing the Repo crumb to navigate back to the Repo Builds page.
- This would align well in the event we want to remove "native" from the URL entirely. (related to comments below)
- Org secrets and shared secrets will be orphaned until an Org landing page is added.

### CODE REVIEW

**Comment by JordanSussman** [comment]
I'd also propose the secrets url and breadcrumb should not contain "native". How about instead having a server and/or user default with the option to override to vault?

**Comment by davidvader** [comment]
@JordanSussman 👍 I agree with you, this should align better with supporting the default engine while also aligning with the recent secrets plugin integration

**Comment by davidvader** [comment]
migrating crumbs only, before making any changes to the URL schema. keeping changes simple for now

**Comment by davidvader** [comment]
### Example

Screen Shot 2020-08-27 at 4 01 29 PM
Screen Shot 2020-08-27 at 4 01 38 PM

### Changes

- removed engine from crumbs
- removed type from crumbs (implied from page context)
- moved "Secrets" crumb to tail
- when adding/viewing ,"Secrets" crumbs redirects to org/repo/shared secrets (respectively)
- on all secrets pages, repo crumb now redirects to repository builds page

**Comment by wass3r** [comment]
i know there are some ideas for org-level pages, but until then, i wonder if we could do something to support navigating to org/shared secrets that's not too involved.

**Review by wass3r — APPROVED** [review]

**Review by kneal — APPROVED** [review]

**Pull request merged**
